/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <common.h>
#include <uart_engine.h>
#include <timer_init.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
  USART3_Init();
  DELAY_OPM_TIMER_INIT(100);
  UINT16 sineWave[1] = {696};
  UINT8 first_send[SIZE_OF_BYTE] = {0, 0, 0, 0, 1};
  UINT8 second_send[SIZE_OF_BYTE] = {1, };
  UINT8 first_transmit, second_transmit;

  while(1){

    //Does UART send the MSB or LSB first?

    ENCODE_FUNC(sineWave[0], first_send, second_send, &first_transmit, &second_transmit);

    USART3_Write(first_transmit);
    DELAY_OPM_TIMER_UPDATE(5000);
    while(!(TIM2_COMPLETE_EVENT)){}

    USART3_Write(second_transmit);
    DELAY_OPM_TIMER_UPDATE(5000);
    while(!(TIM2_COMPLETE_EVENT)){}
  }
}
